name: Architect Destroy Preview
description: Easily destroy a deployed component and environment on the Architect Cloud
author: architect-team
branding:
  icon: cloud-off
  color: orange

inputs:
  email:
    required: true
  password:
    required: true
  account:
    required: true
  environment:
    required: true
  component_name:
    required: true

runs:
  using: 'composite'
  steps:
    - run: npm install -g @architect-io/cli@0.7.2
      shell: bash
    - run: architect login -e ${{ inputs.email }} -p ${{ inputs.password }}
      shell: bash
    - run: architect destroy --auto_approve -a ${{ inputs.account }} -e ${{ inputs.environment }} -c ${{ inputs.component_name }}:${{ inputs.environment }}
      shell: bash
    - run: architect env:destroy --auto_approve ${{ inputs.environment }} -a ${{ inputs.account }}
      shell: bash
