name: Architect Destroy Environment

env:
  ARCHITECT_USERNAME:
  ARCHITECT_PASSWORD:
  ARCHITECT_ACCOUNT:

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  architect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: format environment name
        run: ::set-env name=ARCHITECT_ENVIRONMENT::"${$GITHUB_REF//\//-}"
      - name: login
        run: architect login -u $ARCHITECT_USERNAME -p $ARCHITECT_PASSWORD
      - name: destroy preview
        run: architect destroy -e $ARCHITECT_ENVIRONMENT -a $ARCHITECT_ACCOUNT --auto_approve
      - name: destroy environment
        run: architect environments:destroy $ARCHITECT_ENVIRONMENT --auto_approve
