name: Architect Destroy Environment
description: Easily destroy a deployed component and environment on the Architect Cloud
author: architect-team
branding:
  icon: cloud-off
  color: orange

inputs:
  USERNAME:
    required: true
  PASSWORD:
    required: true
  ACCOUNT:
    required: true
  ENVIRONMENT:
    required: true
  COMPONENT_NAME:
    required: true

runs:
  using: 'composite'
  steps:
    - run: npm install -g @architect-io/cli@0.6.1
      shell: bash
    - run: architect login -u ${{ inputs.USERNAME }} -p ${{ inputs.PASSWORD }}
      shell: bash
    - run: architect destroy --auto_approve -a ${{ inputs.ACCOUNT }} -e ${{ inputs.ENVIRONMENT }} -c ${{ inputs.COMPONENT_NAME }}
      shell: bash
    - run: architect env:destroy --auto_approve ${{ inputs.ENVIRONMENT }} -a ${{ inputs.ACCOUNT }}
